export const REAL_BOOKS = [
  { id: 11,
  description: "Paulo Coelho's masterpiece tells the mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure. His quest leads him to riches far different—and far more satisfying—than he ever imagined. The Alchemist is an eternal testament to the transforming power of our dreams and the importance of listening to our hearts.",
    title: "Rich Dad Poor Dad", author: "Robert Kiyosaki", genre: "Finance", cover: "https://covers.openlibrary.org/b/id/10521287-L.jpg",
 isPurchased: false,
  price:200,

  trialStarted: new Date(),
  trialEnds: new Date(),
},
  { id:10,
  description: "Paulo Coelho's masterpiece tells the mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure. His quest leads him to riches far different—and far more satisfying—than he ever imagined. The Alchemist is an eternal testament to the transforming power of our dreams and the importance of listening to our hearts.",
    title: "Atomic Habits", author: "James Clear", genre: "Self-help", cover: "https://covers.openlibrary.org/b/id/9251746-L.jpg",
 isPurchased: false,
  trialStarted: new Date(),
  price:100,
  trialEnds: new Date(),
},
  { id:9,
  description: "Paulo Coelho's masterpiece tells the mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure. His quest leads him to riches far different—and far more satisfying—than he ever imagined. The Alchemist is an eternal testament to the transforming power of our dreams and the importance of listening to our hearts.",
    title: "The Alchemist", author: "Paulo Coelho", genre: "Fiction", cover: "https://covers.openlibrary.org/b/id/8231994-L.jpg",
 isPurchased: false,
  price:103,

  trialStarted: new Date(),
  trialEnds: new Date()+2, },
  { id: 8,
  description: "Paulo Coelho's masterpiece tells the mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure. His quest leads him to riches far different—and far more satisfying—than he ever imagined. The Alchemist is an eternal testament to the transforming power of our dreams and the importance of listening to our hearts.",
    
    title: "Harry Potter & The Philosopher's Stone", author: "J.K. Rowling", genre: "Fantasy", cover: "https://covers.openlibrary.org/b/id/7984916-L.jpg",
 isPurchased: false,
  trialStarted: new Date(),
  trialEnds: new Date(),
},
  { id:7,
  description: "Paulo Coelho's masterpiece tells the mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure. His quest leads him to riches far different—and far more satisfying—than he ever imagined. The Alchemist is an eternal testament to the transforming power of our dreams and the importance of listening to our hearts.",
  price:120,
    
    title: "48 Laws of Power",
  description: "Paulo Coelho's masterpiece tells the mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure. His quest leads him to riches far different—and far more satisfying—than he ever imagined. The Alchemist is an eternal testament to the transforming power of our dreams and the importance of listening to our hearts.",
    author: "Robert Greene", genre: "Strategy", cover: "https://covers.openlibrary.org/b/id/240726-L.jpg",
 isPurchased: false,
  trialStarted: new Date(),
  trialEnds: new Date(),
},
];